server:
  port: 8000

url:
  frontend: http://localhost:4200
  backend: http://localhost:8000


# This part in .yaml file is for the h2 JDBC connection establishment
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:file:C:\Users\ASUS\Desktop\Final_Submission_P2_Proj_23\P2_Proj_2023\ImageDB
    driverClassName: org.h2.Driver
    username: sa
    password: